### ISSUE TITLE
train on ETH3D dataset

### ISSUE THREAD

**Issue by TWang1017** [FangjinhuaWang/PatchmatchNet#70]
Hi,

I downloaded the ETH3D dataset from MVSNET repo and use 'convet_eth3d_dataset.py' to process it.

However, i encountered an error during the training process.

Traceback (most recent call last):
  File "c:\Users\SmartLab\Desktop\dl_recon_semantics\codes\Recon\PatchmatchNet-main\train.py", line 313, in <module>
    train(input_args, pmnet_model, train_loader, test_loader, pmnet_optimizer, epoch_start)
  File "c:\Users\SmartLab\Desktop\dl_recon_semantics\codes\Recon\PatchmatchNet-main\train.py", line 41, in train
    process_samples(args, train_sample, "train", logger, model, train_image_loader, optimizer, epoch_idx)
  File "c:\Users\SmartLab\Desktop\dl_recon_semantics\codes\Recon\PatchmatchNet-main\train.py", line 92, in process_samples
    for batch_idx, sample in enumerate(image_loader):
  File "C:\Users\SmartLab\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 652, in __next__
    data = self._next_data()
  File "C:\Users\SmartLab\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1347, in _next_data
    return self._process_data(data)
  File "C:\Users\SmartLab\anaconda3\lib\site-packages\torch\utils\data\dataloader.py", line 1373, in _process_data
    data.reraise()
  File "C:\Users\SmartLab\anaconda3\lib\site-packages\torch\_utils.py", line 461, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "C:\Users\SmartLab\anaconda3\lib\site-packages\torch\utils\data\_utils\worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "C:\Users\SmartLab\anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "C:\Users\SmartLab\anaconda3\lib\site-packages\torch\utils\data\_utils\fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "c:\Users\SmartLab\Desktop\dl_recon_semantics\codes\Recon\PatchmatchNet-main\datasets\mvs.py", line 95, in __getitem__
    depth_gt = read_map(depth_gt_filename, self.max_dim).transpose([2, 0, 1]).copy()
ValueError: axes don't match array

any help is much appreciated.

**Comment by HiRenZeHui** [comment]
Hello, I also encountered this problem. Have you solved it

**Comment by FangjinhuaWang** [comment]
I did not try with training on eth3d. But seems like the problem is that the array only has two dimension, so it pops out error when doing 'transpose([2, 0, 1])'

**Comment by lin-fangzhou** [comment]
In that case, can we only use the DTU dataset for training? Are there other existing data sets that can be used to train new networks.

**Comment by lin-fangzhou** [comment]
> Hello, I also encountered this problem. Have you solved it

Hello, have you successfully used ETH3D training patchmatchnet?

**Comment by TWang1017** [comment]
> In that case, can we only use the DTU dataset for training? Are there other existing data sets that can be used to train new networks.



> Hello, I also encountered this problem. Have you solved it

I did not proceed with it. ETH3D is gray and the dimension is not divisible by 8 if I remember correctly while Patchmatchnet accepts RGBs with dimension divisible by 8

**Comment by TWang1017** [comment]
> In that case, can we only use the DTU dataset for training? Are there other existing data sets that can be used to train new networks.

Can try BlendedMVS

**Comment by Alive-zyxs** [comment]
@TWang1017 Hi,Have you train it on BlendedMVS?I download the dataset and  converted it to the same data structure as the Dtu training set.But I got problems when training,as shown below:
![image](https://user-images.githubusercontent.com/119551869/232749976-c3bfe43c-5855-4e77-b4c7-480e2175a14b.png)
（(My memory should be enough, I didn't have problems training with the DTU dataset before)
thanks very much!

**Comment by Alive-zyxs** [comment]
@TWang1017 Hi,Have you train it on BlendedMVS?I download the dataset and converted it to the same data structure as the Dtu training set.But I got problems when training,as shown below:
![image](https://user-images.githubusercontent.com/119551869/232750631-46d9b48f-18c6-4924-9415-de5e530ac583.png)

（(My memory should be enough, I didn't have problems training with the DTU dataset before)
thanks very much!

**Comment by TWang1017** [comment]
> > > In that case, can we only use the DTU dataset for training? Are there other existing data sets that can be used to train new networks.
> > 
> > 
> > Can try BlendedMVS
> 
> I am trying BlendedMVS，and I get the same problem as you.I checked the pfm format of the depth map and found that it was grayscale rather than rgb.

BlendedMVS is fine, I trained on BlendedMVS with no  problem.

**Comment by Alive-zyxs** [comment]
> > > > In that case, can we only use the DTU dataset for training? Are there other existing data sets that can be used to train new networks.
> > > 
> > > 
> > > Can try BlendedMVS
> > 
> > 
> > I am trying BlendedMVS，and I get the same problem as you.I checked the pfm format of the depth map and found that it was grayscale rather than rgb.
> 
> BlendedMVS is fine, I trained on BlendedMVS with no problem.



> > > > In that case, can we only use the DTU dataset for training? Are there other existing data sets that can be used to train new networks.
> > > 
> > > 
> > > Can try BlendedMVS
> > 
> > 
> > I am trying BlendedMVS，and I get the same problem as you.I checked the pfm format of the depth map and found that it was grayscale rather than rgb.
> 
> BlendedMVS is fine, I trained on BlendedMVS with no problem.

How do you train? Can we contact in another way (such as email or wechat)? Thank you very much！

**Comment by TWang1017** [comment]
> > > > > In that case, can we only use the DTU dataset for training? Are there other existing data sets that can be used to train new networks.
> > > > 
> > > > 
> > > > Can try BlendedMVS
> > > 
> > > 
> > > I am trying BlendedMVS，and I get the same problem as you.I checked the pfm format of the depth map and found that it was grayscale rather than rgb.
> > 
> > 
> > BlendedMVS is fine, I trained on BlendedMVS with no problem.
> 
> > > > > In that case, can we only use the DTU dataset for training? Are there other existing data sets that can be used to train new networks.
> > > > 
> > > > 
> > > > Can try BlendedMVS
> > > 
> > > 
> > > I am trying BlendedMVS，and I get the same problem as you.I checked the pfm format of the depth map and found that it was grayscale rather than rgb.
> > 
> > 
> > BlendedMVS is fine, I trained on BlendedMVS with no problem.
> 
> How do you train? Can we contact in another way (such as email or wechat)? Thank you very much！

you can send me your email or WeChat and I will contact you,

**Comment by Alive-zyxs** [comment]
My wechat: zs18713441977. Thank you!



---- Replied Message ----
| From | Tao ***@***.***> |
| Date | 04/21/2023 21:06 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [FangjinhuaWang/PatchmatchNet] train on ETH3D dataset (Issue #70) |

In that case, can we only use the DTU dataset for training? Are there other existing data sets that can be used to train new networks.

Can try BlendedMVS

I am trying BlendedMVS，and I get the same problem as you.I checked the pfm format of the depth map and found that it was grayscale rather than rgb.

BlendedMVS is fine, I trained on BlendedMVS with no problem.

In that case, can we only use the DTU dataset for training? Are there other existing data sets that can be used to train new networks.

Can try BlendedMVS

I am trying BlendedMVS，and I get the same problem as you.I checked the pfm format of the depth map and found that it was grayscale rather than rgb.

BlendedMVS is fine, I trained on BlendedMVS with no problem.

How do you train? Can we contact in another way (such as email or wechat)? Thank you very much！

you can send me your email or WeChat and I will contact you,

**Comment by ym19196018395** [comment]
> > > > > > In that case, can we only use the DTU dataset for training? Are there other existing data sets that can be used to train new networks.
> > > > > 
> > > > > 
> > > > > Can try BlendedMVS
> > > > 
> > > > 
> > > > I am trying BlendedMVS，and I get the same problem as you.I checked the pfm format of the depth map and found that it was grayscale rather than rgb.
> > > 
> > > 
> > > BlendedMVS is fine, I trained on BlendedMVS with no problem.
> > 
> > 
> > > > > > In that case, can we only use the DTU dataset for training? Are there other existing data sets that can be used to train new networks.
> > > > > 
> > > > > 
> > > > > Can try BlendedMVS
> > > > 
> > > > 
> > > > I am trying BlendedMVS，and I get the same problem as you.I checked the pfm format of the depth map and found that it was grayscale rather than rgb.
> > > 
> > > 
> > > BlendedMVS is fine, I trained on BlendedMVS with no problem.
> > 
> > 
> > How do you train? Can we contact in another way (such as email or wechat)? Thank you very much！
> 
> you can send me your email or WeChat and I will contact you,



> > > > > > In that case, can we only use the DTU dataset for training? Are there other existing data sets that can be used to train new networks.
> > > > > 
> > > > > 
> > > > > Can try BlendedMVS
> > > > 
> > > > 
> > > > I am trying BlendedMVS，and I get the same problem as you.I checked the pfm format of the depth map and found that it was grayscale rather than rgb.
> > > 
> > > 
> > > BlendedMVS is fine, I trained on BlendedMVS with no problem.
> > 
> > 
> > > > > > In that case, can we only use the DTU dataset for training? Are there other existing data sets that can be used to train new networks.
> > > > > 
> > > > > 
> > > > > Can try BlendedMVS
> > > > 
> > > > 
> > > > I am trying BlendedMVS，and I get the same problem as you.I checked the pfm format of the depth map and found that it was grayscale rather than rgb.
> > > 
> > > 
> > > BlendedMVS is fine, I trained on BlendedMVS with no problem.
> > 
> > 
> > How do you train? Can we contact in another way (such as email or wechat)? Thank you very much！
> 
> you can send me your email or WeChat and I will contact you,

@TWang1017 Hello author, could I ask you how to train on BlendedMVS data? Thank you.
